# Generated by Django 5.2.7 on 2025-10-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('title', models.CharField(help_text='Slaytın ana başlığı (büyük yazılacak)', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Başlığın altındaki daha küçük metin (isteğe bağlı)', max_length=300)),
                ('button_text', models.CharField(default='Keşfet', help_text='Slayt üzerindeki butonun metni', max_length=50)),
                ('button_link', models.CharField(default='/products/', help_text='Butona tıklandığında gidilecek adres (örn: /products/erkek/)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Gösterim sırası (küçük olan önce gelir)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
