# Generated by Django 5.2.7 on 2025-11-20 06:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Duyuru Metni')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Duyuru Linki (İsteğe bağlı)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Duyuru Bandı',
                'verbose_name_plural': 'Duyuru Bantları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('49.99'), max_digits=10, verbose_name='Sabit Kargo Ücreti')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Ücretsiz Kargo Limiti (Bu tutar ve üzeri)')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık')),
                ('button_text', models.CharField(max_length=50, verbose_name='Buton Metni')),
                ('button_link', models.CharField(max_length=255, verbose_name='Buton Linki')),
                ('slide_type', models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], default='image', max_length=10, verbose_name='Slayt Tipi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Resim (Resim tipi veya Video kapağı)')),
                ('video', models.FileField(blank=True, null=True, upload_to='slides/videos/', verbose_name='Video (Video tipi)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Slayt',
                'verbose_name_plural': 'Slaytlar',
                'ordering': ['order'],
            },
        ),
    ]
