# Generated by Django 5.2.7 on 2025-10-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(default='Genel Ayarlar', editable=False, max_length=100, unique=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Firmanızın Instagram profil linki (örn: https://www.instagram.com/auraluna)', max_length=250, null=True, verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
