# Generated by Django 5.2.7 on 2025-11-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], default='image', max_length=10, verbose_name='Slayt Türü')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/', verbose_name='Slayt Resmi')),
                ('video', models.FileField(blank=True, help_text='Eğer video seçerseniz resim yerine video oynatılır.', null=True, upload_to='hero_videos/', verbose_name='Slayt Videosu (MP4)')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Alt Başlık')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Yazısı')),
                ('button_link', models.CharField(blank=True, help_text='Slayta tıklandığında gidilecek adres (örn: /products/erkek/)', max_length=200, null=True, verbose_name='Yönlendirilecek Link (URL)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Slaytı',
                'verbose_name_plural': 'Ana Sayfa Slaytları',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AlterModelOptions(
            name='announcementbanner',
            options={'ordering': ('order',), 'verbose_name': 'Duyuru Bandı', 'verbose_name_plural': 'Duyuru Bantları'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta Adresi'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Linki'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter/X Linki'),
        ),
        migrations.AlterField(
            model_name='announcementbanner',
            name='link',
            field=models.CharField(blank=True, help_text='Tıklandığında gidilecek adres', max_length=255, null=True, verbose_name='Link (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='announcementbanner',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Duyuru Mesajı'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ücretsiz Kargo Limiti'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Linki'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kargo Ücreti'),
        ),
    ]
