# Generated by Django 5.2.7 on 2025-10-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Sitenin en üstünde görünecek metin (örn: Tüm ürünlerde %20 indirim!)', max_length=250, verbose_name='Duyuru Mesajı')),
                ('link', models.URLField(blank=True, help_text='Banda tıklandığında gidilecek adres (boş bırakılırsa tıklanmaz)', max_length=250, null=True, verbose_name="Bağlantı URL'si (İsteğe Bağlı)")),
                ('is_active', models.BooleanField(default=False, help_text='Bu bandın sitede gösterilip gösterilmeyeceğini belirler.', verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duyuru Bandı',
                'verbose_name_plural': 'Duyuru Bantları',
                'ordering': ['-created_at'],
            },
        ),
    ]
