# Generated by Django 5.2.7 on 2025-10-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_announcementbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order'], 'verbose_name': 'Slayt', 'verbose_name_plural': 'Slaytlar'},
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], default='image', max_length=10, verbose_name='Slayt Türü'),
        ),
        migrations.AddField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, help_text='Otomatik oynatılacak, sessiz ve döngüde olacak video (MP4 önerilir).', null=True, upload_to='slides/videos/', verbose_name='Video Dosyası (Sadece Video Slaytları İçin)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_link',
            field=models.CharField(default='/products/', help_text='Butona tıklandığında gidilecek adres (örn: /products/erkek/)', max_length=200, verbose_name='Buton Linki'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_text',
            field=models.CharField(default='Keşfet', help_text='Slayt üzerindeki butonun metni', max_length=50, verbose_name='Buton Metni'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Resim (Sadece Resim Slaytları İçin)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Gösterim sırası (küçük olan önce gelir)', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Başlığın altındaki daha küçük metin (isteğe bağlı)', max_length=300, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(help_text='Slaytın ana başlığı (büyük yazılacak)', max_length=200, verbose_name='Başlık'),
        ),
    ]
