# Generated by Django 5.2.7 on 2025-11-13 04:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_slide_options_slide_slide_type_slide_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementbanner',
            options={'ordering': ['order'], 'verbose_name': 'Duyuru Bandı', 'verbose_name_plural': 'Duyuru Bantları'},
        ),
        migrations.RemoveField(
            model_name='announcementbanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='setting_name',
        ),
        migrations.AddField(
            model_name='announcementbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Ücretsiz Kargo Limiti (Bu tutar ve üzeri)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('49.99'), max_digits=10, verbose_name='Sabit Kargo Ücreti'),
        ),
        migrations.AddField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='announcementbanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='announcementbanner',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Duyuru Linki (İsteğe bağlı)'),
        ),
        migrations.AlterField(
            model_name='announcementbanner',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Duyuru Metni'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_link',
            field=models.CharField(max_length=255, verbose_name='Buton Linki'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_text',
            field=models.CharField(max_length=50, verbose_name='Buton Metni'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Resim (Resim tipi veya Video kapağı)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], default='image', max_length=10, verbose_name='Slayt Tipi'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slides/videos/', verbose_name='Video (Video tipi)'),
        ),
    ]
