# Generated by Django 5.2.7 on 2025-11-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Bildirim Gönderildi mi?')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='products.productvariant', verbose_name='Varyasyon')),
            ],
            options={
                'verbose_name': 'Stok Bildirimi',
                'verbose_name_plural': 'Stok Bildirimleri',
                'ordering': ('-created_at',),
            },
        ),
    ]
