# Generated by Django 5.2.7 on 2025-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Bootstrap ikon sınıfı (örn: bi-tags-fill, bi-gem)', max_length=50, null=True, verbose_name='İkon Sınıfı'),
        ),
    ]
