# Generated by Django 5.2.7 on 2025-11-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Renk Adı')),
                ('hex_code', models.CharField(default='#FFFFFF', help_text='Örn: #FFFFFF (Beyaz için)', max_length=7, verbose_name='Hex Kodu')),
            ],
            options={
                'verbose_name': 'Renk',
                'verbose_name_plural': 'Renkler',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Beden Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sıralama (örn: S=1, M=2, L=3)')),
            ],
            options={
                'verbose_name': 'Beden',
                'verbose_name_plural': 'Bedenler',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.color', verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.size', verbose_name='Beden'),
        ),
    ]
