# Generated by Django 5.2.7 on 2025-11-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_color_alter_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Ana kapak fotoğrafı (Opsiyonel)', null=True, upload_to='products/'),
        ),
    ]
