# Generated by Django 5.2.7 on 2025-11-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_color_size_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_products', to='products.category', verbose_name='İkincil Kategoriler (Etiketler)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Ana Kategori'),
        ),
    ]
